language: java
script: mvn clean deploy
env:
  global:
    secure: CNPu3eHuKl82B7mMB3SOn/52U65F56ccD5Wa5RrUJa+a0Fnu46U3TzwKqPDNR71tMOq6bh1w6Ri6Kkri3ACnsDlhPZAxDyD6EQTCqfdvzWQciIu8T0RU9vIc2l56ei7BrY05aPiPK8z4f0l8KolhUJTB+efTQw2C8eEOzBgVNzw=
